name: wordshop app workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: [self-hosted, linux, windows-latest, ubuntu-latest]
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # install the latest python version

      - name: execute py script # app.py
        env: 
          OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
        run: python app.py
