name: wordshop app workflow

on: [push, fork, pull_request] 

steps:
 - name: app.py
   with:
       OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
   env:
       OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}

jobs:
  build:
    runs-on: [windows-latest, ubuntu-latest, linux]
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # install the latest python version

      - name: execute py script # app.py
        env: 
          OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
        run: python app.py
